version: "2.4"

volumes:
  db-data:
    external: false


services:

  db:
    image: mariadb:10.11.16
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      TZ: +00:00
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme

  app:
    restart: unless-stopped
    build: ./steve
    ports:
      - "8180:8180"
      - "8443:8443"
    depends_on:
      - db
    volumes:
      - ./steve/:/code
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8180/steve/manager"]
      interval: 60s
      timeout: 10s
      retries: 20
      start_period: 180s
    
  # charge_point:
  #   restart: unless-stopped
  #   build: ./ocpp-charge-point-api
  #   ports:
  #     - "9000:9000"

  cp-simulator:
    restart: unless-stopped
    build: ./cp-simulator
    depends_on:
      app:
        condition: service_healthy

  tcpdump:
    image: nicolaka/netshoot
    depends_on:
      - app
    command: "tcpdump -i eth0 -w /data/poc-ocpp.pcap"
    network_mode: service:app
    volumes:
      - $PWD/data:/data