FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the attack script
COPY csms_attacker.py .

CMD [ "python3", "csms_attacker.py" ]
